package homework.homework15;

public enum Position {
    PEDIATRICIAN,
    GYNECOLOGIST,
    PSYCHIATRIST,
    CARDIOLOGIST,
    DERMATOLOGIST,
    ENDOCRINOLOGIST,
    GASTROENTEROLOGIST,
    OPHTHALMOLOGIST
}
